Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = "ubuntu/bionic64"  
  end

  config.vm.define "node1" do |subconfig|
    subconfig.vm.box = "ubuntu/bionic64"  
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2
  SHELL
  config.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "node2" do |subconfig|
    subconfig.vm.box = "centos/7"
  end
end

